Ground_Handlng.Web/Areas/Operational/Controllers/ManagementContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ground_Handlng.DataObjects.Data.Context;
using Ground_Handlng.DataObjects.Models.Operational;
using Microsoft.AspNetCore.Http;
using Ground_Handlng.DataObjects.Models.Others;
using Microsoft.AspNetCore.Hosting;

namespace Ground_Handlng.Web.Areas.Operational.Controllers
{
    [Area("Operational")]
    public class ManagementContactsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ManagementContact _ManagementContacts;
        private IHostingEnvironment _env;
        public ManagementContactsController(ApplicationDbContext context, IHostingEnvironment env)
        {
            _context = context;
            _ManagementContacts = new ManagementContact(_context);
            _env = env;
        }

        // GET: Operational/ManagementContacts
        public async Task<IActionResult> Index()
        {
            if (TempData["SuccessMessage"] != null)
            {
                ViewBag.SuccessMessage = TempData["SuccessMessage"].ToString();
            }
            return View(_ManagementContacts.GetList().Result.Cast<ManagementContact>());
        }



        // GET: Operational/ManagementContacts/Create
        public PartialViewResult Create()
        {
            return PartialView();
        }

        // POST: Operational/ManagementContacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ManagementContact model, IFormCollection formCollection)
        {
            if (ModelState.IsValid)
            {

                _ManagementContacts.FullName = model.FullName;
                _ManagementContacts.Position = model.Position;
                _ManagementContacts.PhoneNumber = model.PhoneNumber;
                _ManagementContacts.Email = model.Email;
                _ManagementContacts.WorkingArea = model.WorkingArea;

                var result = await _ManagementContacts.Save() as DatabaseOperationResponse;
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        // GET: Operational/ManagementContacts/Edit/5
        public PartialViewResult Edit(long id)
        {
            if (id != 0)
            {
                _ManagementContacts.Id = id;
                var FAQ = _ManagementContacts.Refresh().Result as ManagementContact;

                return PartialView(FAQ);
            }
            return PartialView();
        }

        // POST: Operational/ManagementContacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, ManagementContact model, IFormCollection formCollection)
        {
            if (ModelState.IsValid)
            {
                _ManagementContacts.Id = model.Id;
                _ManagementContacts.FullName = model.FullName;
                _ManagementContacts.Position = model.Position;
                _ManagementContacts.PhoneNumber = model.PhoneNumber;
                _ManagementContacts.Email = model.Email;
                _ManagementContacts.WorkingArea = model.WorkingArea;
                
                var result = await _ManagementContacts.Update() as DatabaseOperationResponse;
                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");

        }
        public async Task<JsonResult> Delete(long id)
        {
            if (id != 0)
            {
                var ManagementContact = await _context.ManagementContacts.AsNoTracking().FirstOrDefaultAsync(con => con.Id == id);

                _ManagementContacts.Id = ManagementContact.Id;
                _ManagementContacts.FullName = ManagementContact.FullName;
                _ManagementContacts.Position = ManagementContact.Position;
                _ManagementContacts.PhoneNumber = ManagementContact.PhoneNumber;
                _ManagementContacts.Email = ManagementContact.Email;
                _ManagementContacts.WorkingArea = ManagementContact.WorkingArea;

                var result = await _ManagementContacts.Delete() as DatabaseOperationResponse;
                return new JsonResult(result);
            }
            return new JsonResult(null);
        }

        [HttpGet]
        public PartialViewResult Upload()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<ActionResult> Upload(IFormFile files, ManagementContact ManagementContacts)
        {
            var SavedContacts = _context.ManagementContacts.ToList();
            //if (ModelState.IsValid)
            //{
            try
            {
                string filePath = string.Empty;
                try
                {
                    if (files != null)
                    {
                        string path = System.IO.Path.Combine(_env.WebRootPath,"Uploads");                        
                        if (!Directory.Exists(path))
                        {
                            Directory.CreateDirectory(path);
                        }
                        filePath = Path.Combine(path,Path.GetFileName(files.FileName));
                        string extension = Path.GetExtension(files.FileName);
                        var streamReader = new StreamReader(files.OpenReadStream());                  
                        var csvcontactData = streamReader.ReadToEndAsync().Result;
                        
                            foreach (string row in csvcontactData.Split('\n'))
                            {
                                string rowString = row.ToLower();
                                rowString.Trim();
                                if (rowString.Contains("full name"))
                                {
                                    continue;
                                }
                                if (!string.IsNullOrEmpty(row))
                                {
                                    ManagementContact managementContact = null;
                                    if (SavedContacts?.Count > 0)
                                    {
                                        if (!string.IsNullOrEmpty(row.Split(',')[3]))
                                        {
                                        managementContact = SavedContacts.Where(c => c.Email.Equals(row.Split(',')[3], StringComparison.OrdinalIgnoreCase)).FirstOrDefault();
                                        }
                                        else
                                            continue;
                                    }
                                    if (managementContact == null)
                                    {

                                    ManagementContact Mcontact = new ManagementContact()
                                    {

                                        FullName = row.Split(',')[1],
                                        Position = row.Split(',')[2],
                                        PhoneNumber = row.Split(',')[4],
                                        Email = await EmailNormilizer(row.Split(',')[3]),
                                        WorkingArea = row.Split(',')[0].Trim(),
                                        Status = RecordStatus.Active,
                                };
                                    _context.ManagementContacts.Add(Mcontact);
                                    _context.SaveChanges();

                                }
                                    else
                                    {
                                    managementContact.WorkingArea = row.Split(',')[0];
                                    managementContact.FullName = row.Split(',')[1];
                                    managementContact.Position = row.Split(',')[2];
                                    managementContact.Email = await EmailNormilizer(row.Split(',')[3]);
                                    managementContact.PhoneNumber = row.Split(',')[4];
                                    managementContact.Status = RecordStatus.Active;

                                    _context.Entry(managementContact).State = EntityState.Modified;
                                    _context.SaveChanges();

                                    //return RedirectToAction("Index");
                                    }
                                }
                            }
                    }
                }
                catch (Exception ex)
                {
                    ex.ToString();
                }


                return RedirectToAction("Index");
            }
            catch (System.IndexOutOfRangeException e)  // CS0168
            {
                Console.WriteLine(e.Message);
                throw new System.ArgumentOutOfRangeException("index parameter is out of range.", e);
            }
            catch (Exception ex)
            {

            }
            //}
            return RedirectToAction("Index");
        }
        public async Task<string> EmailNormilizer(string email)
        {
            var crewmail = string.Empty;
            if (!string.IsNullOrEmpty(email))// && IsValidEmail(email))
            {
                crewmail = Regex.Replace(email.Trim(), @"\t|\n|\r", "");
            }

Ground_Handlng.Web/Areas/Operational/Views/ManagementContacts/Create.cshtml
@model Ground_Handlng.DataObjects.Models.Operational.ManagementContact

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{

}
<link rel="stylesheet" href="~/AdminLTE/dist/css/adminlte.min.css" />
<link rel="stylesheet" href="~/AdminLTE/plugins/bootstrap/css/bootstrap.min.css" />

<style>
    input.error {
        border-color: #f00 !important;
    }

    small.required {
        color: #f00;
    }
</style>

<section class="content">
    <div class="card">
        <div class="card-body">
            @using (Html.BeginForm(FormMethod.Post, new { @class = "form-horizontal", @id = "validate", @enctype = "multipart/form-data", @role = "form" }))
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="callout callout-danger error-box-holder" id="general-error" style="display:none">
                    <h4> Please correct the following errors and sumbit again </h4>
                    <ul id="errors" class="error-box"></ul>
                </div>
                <div class="form-group">
                    <label asp-for="FullName" class="control-label col-md-3"></label>
                    <div class="col-sm-7">
                        <input for="FullName" class="form-control required" name="FullName" />
                    </div>
                    <span for="FullName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Position" class="control-label col-md-3"></label>
                    <div class="col-sm-7">
                        <input for="Position" class="form-control required" name="Position" />
                    </div>
                    <span for="Position" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label col-md-3"></label>
                    <div class="col-sm-7">
                        <input for="PhoneNumber" class="form-control required" name="PhoneNumber" />
                    </div>
                    <span for="PhoneNumber" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Email" class="control-label col-md-3"></label>
                    <div class="col-sm-7">
                        <input for="Email" class="form-control required" name="Email" />
                    </div>
                    <span for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="WorkingArea" class="control-label col-md-3"></label>
                    <div class="col-sm-7">
                        <input for="WorkingArea" class="form-control required" name="WorkingArea" />
                    </div>
                    <span for="WorkingArea" class="text-danger"></span>
                </div>


                <br />
                <div class="form-group col-md-3">
                    <button type="submit" class="btn btn-success btn-block"> Save </button>
                </div>
            }
        </div>
    </div>
</section>

<script src="~/AdminLTE/plugins/jquery-validation/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">

        $.validator.setDefaults({
            submitHandler: function () {
                $('#general-error').hide();
                $('#errors').empty();
                var formData = new FormData();
                formData.append('url', $('#url')[0].files[0]);
                var other_data = $('#validate').serializeArray();
                $.each(other_data, function (key, input) {
                    formData.append(input.name, input.value);
                });
                $.ajax({
                    url: '/Operational/CostSavingIdeaRequests/Create',
                    type: 'POST',
                    data: formData,
                    processData: false,
                    contentType: false,
                    cache: false,
                    success: function (data) {
                        debugger;
                        if (data.status == "3" || data.status == "4" || data.status == "5") {
                            if (data.status == "3") {
                                swal({
                                    type: 'success',
                                    title: data.message,
                                    showConfirmButton: false,
                                    timer: 3000
                                }).then(() => { window.location = "/Operational/FrequentlyAskedQuestions/Index"; });
                                $('#modal').modal('hide');
                            }
                            else {
                                swal({
                                    type: 'error',
                                    title: data.message,
                                    showConfirmButton: false,
                                    timer: 3000
                                });
                            }
                        }
                    },
                    error: function (data) {
                        window.location = "/Operational/FrequentlyAskedQuestions/Index";
                        swal({
                            type: 'error',
                            title: data.message,
                            showConfirmButton: false,
                            timer: 3000
                        }).then(() => { window.location = "/Operational/FrequentlyAskedQuestions/Index"; });

                    }

                });
            }
        });
        $('#validate').validate({
            ignore: [],
            errorPlacement: function () { },
            invalidHandler: function () {
                setTimeout(function () {
                    $('.nav-tabs a small.required').remove();
                    var validatePane = $('.tab-content.tab-validate .tab-pane:has(input.error)').each(function () {
                        debugger;
                        var id = $(this).attr('id');
                        $('.nav-tabs').find('a[href^="#' + id + '"]').append('<small class="required">***</small>');
                    });
                });
            },
            rules: {
                FullName: {
                    required: true
                },
                Position: {
                    required: true
                },
                PhoneNumber: {
                    required: true
                },
                Email: {
                    required: true
                },
                WorkingArea: {
                    required: true
                },

            },
            messages: {
                FullName: {
                    required: "Please enter a FullName"
                },
                Position: {
                    required: "Please enter a Position",
                },
                PhoneNumber: {
                    required: "Please enter a PhoneNumber"
                },
                Email: {
                    required: "Please enter a Email"
                },
                WorkingArea: {
                    required: "Please enter a WorkingArea"
                },

            },
            errorElement: 'span',
            errorPlacement: function (error, element) {
                error.addClass('invalid-feedback');
                element.closest('.form-group').append(error);
            },
            highlight: function (element, errorClass, validClass) {
                $(element).addClass('is-invalid');
            },
            unhighlight: function (element, errorClass, validClass) {
                $(element).removeClass('is-invalid');
            }

        });


    });
</script>

Ground_Handlng.Web/Areas/Operational/Views/ManagementContacts/Delete.cshtml
@model Ground_Handlng.DataObjects.Models.Operational.ManagementContact

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ManagementContact</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WorkingArea)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WorkingArea)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RevisionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RevisionDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RevisedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RevisedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Ground_Handlng.Web/Areas/Operational/Views/ManagementContacts/Details.cshtml
@model Ground_Handlng.DataObjects.Models.Operational.ManagementContact

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>ManagementContact</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WorkingArea)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WorkingArea)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RevisionDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RevisionDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RevisedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RevisedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Ground_Handlng.Web/Areas/Operational/Views/ManagementContacts/Upload.cshtml
@model Ground_Handlng.DataObjects.Models.Operational.ManagementContact


@using (Html.BeginForm("Upload", "ManagementContacts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="panel panel-default col-lg-12">
        <div class="panel-heading my-1">
            Download a <a href="~/Content/UploadFileTemplate/Contact Info Upload sample file.csv">sample file</a> and compare it to your import file to ensure you have the exact csv file to upload.
        </div>
     
        <div class="panel-body my-3">
            <div class="col-6 my-3">
                <label>
                    <input type="file" class="form-control form-control-lg" accept="csv" name="files" data-val="true" placeholder="Upload Company Contacts">
                </label>
            </div>
            <div class="col-submit my-1">
                <button type="submit" value="Upload" id="upload-btn" class="btn btn-primary">Upload Contacts</button>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
    </div>

}

<style>
    .panel-default > .panel-heading {
        font-size: 15px;
    }
</style>